
services:
  app:
    build: .
    container_name: deep_cleaning_backend_app
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://akshay:qx5g0TK7eDgHczKGAULeJl5CYPmhTWBu@dpg-d6djtbktgctc73cel0mg-a.oregon-postgres.render.com/deepclean
    
    volumes:
      - .:/app
  
  